M48
; DRILL file {KiCad 7.0.7} date Sun Dec 17 00:12:56 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-17T00:12:56-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0469
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0590
%
G90
G05
T1
X7.55Y-3.36
X7.55Y-3.46
X7.55Y-3.56
X7.55Y-3.66
T2
X6.1129Y-3.3379
X7.2728Y-3.3379
T3
X6.0501Y-3.905
X6.9399Y-3.905
T0
M30
